-- MySQL Script generated by MySQL Workbench
-- Tue May 30 19:23:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotelReservations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelReservations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelReservations` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotelReservations` ;

-- -----------------------------------------------------
-- Table `hotelReservations`.`Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`Guests` (
  `Guest_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`Guest_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`Hotel` (
  `Hotel_ID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ZipCode` INT NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Fax` VARCHAR(45) NULL,
  PRIMARY KEY (`Hotel_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`RoomTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`RoomTypes` (
  `Room_Type_ID` INT NOT NULL,
  `Room_Type_Name` VARCHAR(45) NOT NULL,
  `Hotel_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`Room_Type_ID`),
  INDEX `fk_hotelID_roomTypes_idx` (`Hotel_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hotelID_roomTypes`
    FOREIGN KEY (`Hotel_ID`)
    REFERENCES `hotelReservations`.`Hotel` (`Hotel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`PastReservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`PastReservations` (
  `Past_Confirmation_Number` VARCHAR(45) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Arrival_Date` DATE NOT NULL,
  `Departure_Date` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NULL,
  `Guest_ID` INT NULL,
  `Room_Type_ID` INT NULL,
  `Hotel_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`Past_Confirmation_Number`),
  INDEX `fk_guestID_pr_idx` (`Guest_ID` ASC) VISIBLE,
  INDEX `fk_hotelID_pastReservations_idx` (`Hotel_ID` ASC) VISIBLE,
  INDEX `fk_roomTypeID_pastReservations_idx` (`Room_Type_ID` ASC) VISIBLE,
  CONSTRAINT `fk_guestID_pastReservations`
    FOREIGN KEY (`Guest_ID`)
    REFERENCES `hotelReservations`.`Guests` (`Guest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotelID_pastReservations`
    FOREIGN KEY (`Hotel_ID`)
    REFERENCES `hotelReservations`.`Hotel` (`Hotel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roomTypeID_pastReservations`
    FOREIGN KEY (`Room_Type_ID`)
    REFERENCES `hotelReservations`.`RoomTypes` (`Room_Type_ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`Reservations` (
  `Confirmation_Number` VARCHAR(45) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Arrival_Date` DATE NOT NULL,
  `Departure_Date` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NULL,
  `Guest_ID` INT NULL,
  `Room_Type_ID` INT NULL,
  `Hotel_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`Confirmation_Number`),
  INDEX `fk_guestID_reservations_idx` (`Guest_ID` ASC) VISIBLE,
  INDEX `fk_hotelID_reservations_idx` (`Hotel_ID` ASC) VISIBLE,
  INDEX `fk_roomTypeID_reservations_idx` (`Room_Type_ID` ASC) VISIBLE,
  CONSTRAINT `fk_guestID_reservations`
    FOREIGN KEY (`Guest_ID`)
    REFERENCES `hotelReservations`.`Guests` (`Guest_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hotelID_reservations`
    FOREIGN KEY (`Hotel_ID`)
    REFERENCES `hotelReservations`.`Hotel` (`Hotel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roomTypeID_reservations`
    FOREIGN KEY (`Room_Type_ID`)
    REFERENCES `hotelReservations`.`RoomTypes` (`Room_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`PaymentDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`PaymentDetails` (
  `Payment_ID` INT NOT NULL AUTO_INCREMENT,
  `Card_Holder_Name` VARCHAR(45) NOT NULL,
  `CC_Numbers` VARCHAR(45) NOT NULL,
  `Expiration_Date` DATE NOT NULL,
  `CVV` INT NOT NULL,
  `Billing_ZipCode` VARCHAR(45) NOT NULL,
  `Guest_ID` INT NULL,
  `Confirmation_Number` VARCHAR(45) NULL,
  `Past_Confirmation_Number` VARCHAR(45) NULL,
  PRIMARY KEY (`Payment_ID`),
  INDEX `fk_guestID_paymentDetails_idx` (`Guest_ID` ASC) VISIBLE,
  INDEX `fk_confirmationNumber_paymentdetails_idx` (`Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_pastConfirmationNumber_paymentDetails_idx` (`Past_Confirmation_Number` ASC) VISIBLE,
  CONSTRAINT `fk_guestID_paymentDetails`
    FOREIGN KEY (`Guest_ID`)
    REFERENCES `hotelReservations`.`Guests` (`Guest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_confirmationNumber_paymentdetails`
    FOREIGN KEY (`Confirmation_Number`)
    REFERENCES `hotelReservations`.`Reservations` (`Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pastConfirmationNumber_paymentDetails`
    FOREIGN KEY (`Past_Confirmation_Number`)
    REFERENCES `hotelReservations`.`PastReservations` (`Past_Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`Billings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`Billings` (
  `Account_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Amount` DECIMAL(5,2) NOT NULL,
  `Payment_ID` INT NULL,
  `Guest_ID` INT NULL,
  `Past_Confirmation_Number` INT NULL,
  PRIMARY KEY (`Account_ID`),
  INDEX `fk_guestID_billings_idx` (`Guest_ID` ASC) VISIBLE,
  INDEX `fk_pastConfirmationNumber_billings_idx` (`Past_Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_paymentID_billings_idx` (`Payment_ID` ASC) VISIBLE,
  CONSTRAINT `fk_guestID_billings`
    FOREIGN KEY (`Guest_ID`)
    REFERENCES `hotelReservations`.`Guests` (`Guest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pastConfirmationNumber_billings`
    FOREIGN KEY (`Past_Confirmation_Number`)
    REFERENCES `hotelReservations`.`PastReservations` (`Guest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paymentID_billings`
    FOREIGN KEY (`Payment_ID`)
    REFERENCES `hotelReservations`.`PaymentDetails` (`Payment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`BookingReservationMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`BookingReservationMethods` (
  `Booking_Method_ID` INT NOT NULL,
  `Booking_Method_Channel` VARCHAR(45) NOT NULL,
  `Confirmation_Number` VARCHAR(45) NULL,
  `Past_Confirmation_Number` VARCHAR(45) NULL,
  PRIMARY KEY (`Booking_Method_ID`),
  INDEX `fk_confirmationNumber_brm_idx` (`Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_pastConfirmationNumber_brm_idx` (`Past_Confirmation_Number` ASC) VISIBLE,
  CONSTRAINT `fk_confirmationNumber_brm`
    FOREIGN KEY (`Confirmation_Number`)
    REFERENCES `hotelReservations`.`Reservations` (`Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pastConfirmationNumber_brm`
    FOREIGN KEY (`Past_Confirmation_Number`)
    REFERENCES `hotelReservations`.`PastReservations` (`Past_Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`CancelledReservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`CancelledReservations` (
  `Cancelation_Number` VARCHAR(45) NOT NULL,
  `Confirmation_Number` VARCHAR(45) NULL,
  `Hotel_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`Cancelation_Number`),
  INDEX `fk_confirmationNumber_cancelledReservations_idx` (`Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_hotelID_cancelledReservations_idx` (`Hotel_ID` ASC) VISIBLE,
  CONSTRAINT `fk_confirmationNumber_cancelledReservations`
    FOREIGN KEY (`Confirmation_Number`)
    REFERENCES `hotelReservations`.`Reservations` (`Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotelID_cancelledReservations`
    FOREIGN KEY (`Hotel_ID`)
    REFERENCES `hotelReservations`.`Hotel` (`Hotel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`FrontDeskAgents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`FrontDeskAgents` (
  `FrontDeskAgent_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FrontDeskAgent_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`CheckInTransactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`CheckInTransactions` (
  `CheckIn_Trans_ID` INT NOT NULL AUTO_INCREMENT,
  `CheckIn_DateTime` DATETIME NOT NULL,
  `Confirmation_Number` VARCHAR(45) NULL,
  `Payment_ID` INT NULL,
  `FrontDeskAgent_ID` INT NULL,
  PRIMARY KEY (`CheckIn_Trans_ID`),
  INDEX `fk_confirmationNumber_checkInTrans_idx` (`Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_paymentID_checkInTrans_idx` (`Payment_ID` ASC) VISIBLE,
  INDEX `fk_frontDeskAgentID_checkInTrans_idx` (`FrontDeskAgent_ID` ASC) VISIBLE,
  CONSTRAINT `fk_confirmationNumber_checkInTrans`
    FOREIGN KEY (`Confirmation_Number`)
    REFERENCES `hotelReservations`.`Reservations` (`Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paymentID_checkInTrans`
    FOREIGN KEY (`Payment_ID`)
    REFERENCES `hotelReservations`.`PaymentDetails` (`Payment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frontDeskAgentID_checkInTrans`
    FOREIGN KEY (`FrontDeskAgent_ID`)
    REFERENCES `hotelReservations`.`FrontDeskAgents` (`FrontDeskAgent_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelReservations`.`CheckOutTransactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelReservations`.`CheckOutTransactions` (
  `CheckOut_Trans_ID` INT NOT NULL AUTO_INCREMENT,
  `CheckOut_DateTime` DATETIME NOT NULL,
  `Confirmation_Number` VARCHAR(45) NULL,
  `Payment_ID` INT NULL,
  `Account_ID` INT NULL,
  `FrontDeskAgent_ID` INT NULL,
  PRIMARY KEY (`CheckOut_Trans_ID`),
  INDEX `fk_confirmationNumber_checkOutTrans_idx` (`Confirmation_Number` ASC) VISIBLE,
  INDEX `fk_paymentID_checkOutTrans_idx` (`Payment_ID` ASC) VISIBLE,
  INDEX `fk_accountID_checkOutTrans_idx` (`Account_ID` ASC) VISIBLE,
  INDEX `fk_frontDeskAgentID_checkOutTrans_idx` (`FrontDeskAgent_ID` ASC) VISIBLE,
  CONSTRAINT `fk_confirmationNumber_checkOutTrans`
    FOREIGN KEY (`Confirmation_Number`)
    REFERENCES `hotelReservations`.`Reservations` (`Confirmation_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paymentID_checkOutTrans`
    FOREIGN KEY (`Payment_ID`)
    REFERENCES `hotelReservations`.`PaymentDetails` (`Payment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accountID_checkOutTrans`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `hotelReservations`.`Billings` (`Account_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frontDeskAgentID_checkOutTrans`
    FOREIGN KEY (`FrontDeskAgent_ID`)
    REFERENCES `hotelReservations`.`FrontDeskAgents` (`FrontDeskAgent_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
